version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "25000:25000" 
    networks:
      - app-network
    expose:
      - "25000"
  
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  